---
apiVersion: v1
kind: List
items:
  - apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: letsencrypt-prod
      namespace: pomodoro
    spec:
      acme:
        email: letsencrypt@maex.me
        privateKeySecretRef:
          name: letsencrypt-prod
        server: https://acme-v02.api.letsencrypt.org/directory
        solvers:
          - http01:
              ingress: {}
            selector: {}


